### ISSUE TITLE
TypeError: No registered converter was able to produce a C++ rvalue of type int from this Python object of type numpy.int64

### ISSUE THREAD

**Issue by Chunpai** [CAHLR/pyBKT#9]
When I try to run the code with my own dataset, it will generate the following error:

```
data keys: dict_keys(['data', 'starts', 'lengths', 'resources', 'stateseqs'])
data: (1, 6242)
starts: (459,)
lengths: (459,)
resources: (6242,)
stateseqs: (1, 6242)
fitting! each dot is a new EM initialization
.Traceback (most recent call last):
  File "test/morf_model.py", line 54, in <module>
    (fitmodel, log_likelihoods) = EM_fit.EM_fit(fitmodel, data)
  File "../pyBKT/fit/EM_fit.py", line 27, in EM_fit
    result = E_step.run(data, model, result['all_trans_softcounts'], result['all_emission_softcounts'], result['all_initial_softcounts'], 1)
TypeError: No registered converter was able to produce a C++ rvalue of type int from this Python object of type numpy.int64
```

I am not sure which part causes this error. I am using 
Ubuntu 18.04
libboost1.62-all-dev
and the latest numpy 

Hope you could help me resolve this issue. Thanks.

**Comment by Chunpai** [comment]
The solution is easy. Simply set the data and resources as np.int32 dtype.
